### ISSUE TITLE
Exercise set 24

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#22]
https://github.com/csci320/brosekerg/blob/9c778f2f87fa119fbd911151d8a3306542ff0ec3/Exercise%20Set%2024#L108

You need to do a better job of following instructions, with attention to detail. You have not used sequential `_id` values as instructed. (Why jump from 10 to 20?) You have more than the expected number (14) of visit records. You will need to get that straightened out or it won't be feasible to figure out if future results are correct.

**Comment by brosekerg** [comment]
i jumped from 10 to 20 because at the time i was unsure which ID i was on so i jumped ahead to where i knew i was safe. I will go back and change these to where they are correct. I ran into a couple issues where i made a duplicate charlie cadillac, and the student_id field was a cause for my confusion because at the time i didnt know it belonged to a seperate table so it was able to have the same number ID as the regular IDs. I will correct this

**Comment by brosekerg** [comment]
i fixed these issues. all the data is correct its just not sorted in ascending order. i cant fix this because it doesnt let me change around the table contents because of the strict _id enforcer. so if you are still unhappy with this the only fix i see is completely deleting the visit table and doing it again from scratch. Which i would rather not do because all of my data is now correct and that would be very tedious, because any lookup i do on the table will still produce the correct results now

**Comment by smattingly** [comment]
Don't close Issues in this repository. I close them when I have examined and approved the fix.

**Comment by smattingly** [comment]
It looks like you have the correct number of `visit` documents now, so we'll call this good and deal with any remaining problems if they show up in other exercise results.
